import { useEffect, useMemo, useRef, useState } from "react";
import api from "../services/api";
import "./FloorMap.css";
const KEY="visionguard.floorMaps.v2";
export default function FloorMap(){
 const [cameras,setCameras]=useState([]),[mapName,setMapName]=useState(localStorage.getItem(`${KEY}.name`)||"Main Floor"),[image,setImage]=useState(localStorage.getItem(`${KEY}.image`)||""),[positions,setPositions]=useState(JSON.parse(localStorage.getItem(`${KEY}.positions`)||"{}")),[selected,setSelected]=useState(""),[nvr,setNvr]=useState("ALL"); const mapRef=useRef(null);
 const load=()=>api.get("/cameras").then(r=>setCameras(Array.isArray(r.data)?r.data:[])).catch(()=>setCameras([])); useEffect(()=>{load();const t=setInterval(load,15000);return()=>clearInterval(t)},[]);
 useEffect(()=>{localStorage.setItem(`${KEY}.name`,mapName);localStorage.setItem(`${KEY}.image`,image);localStorage.setItem(`${KEY}.positions`,JSON.stringify(positions))},[mapName,image,positions]);
 const nvrs=[...new Set(cameras.map(c=>c.nvr))]; const visible=useMemo(()=>cameras.filter(c=>nvr==="ALL"||c.nvr===nvr),[cameras,nvr]);
 const upload=e=>{const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>setImage(String(r.result));r.readAsDataURL(f)};
 const place=e=>{if(!selected||!mapRef.current)return;const r=mapRef.current.getBoundingClientRect();const x=((e.clientX-r.left)/r.width)*100,y=((e.clientY-r.top)/r.height)*100;setPositions(p=>({...p,[selected]:{x,y}}))};
 return <div className="vg-floor-page"><div className="vg-floor-head"><div><div className="vg-eyebrow">SITE VISUALIZATION</div><h1>Floor Map Control</h1><p>Upload your floor plan and position cameras from any NVR. Locations are saved locally in this browser.</p></div><label className="vg-upload-btn">Upload Floor Plan<input type="file" accept="image/*" onChange={upload}/></label></div><div className="vg-floor-toolbar"><input value={mapName} onChange={e=>setMapName(e.target.value)} placeholder="Map name"/><select value={nvr} onChange={e=>setNvr(e.target.value)}><option value="ALL">All NVRs</option>{nvrs.map(x=><option key={x}>{x}</option>)}</select><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Select camera to place</option>{visible.map(c=><option key={`${c.nvr}:${c.id}`} value={`${c.nvr}:${c.id}`}>{c.name} — {c.nvr} CH-{c.id}</option>)}</select><button onClick={()=>setPositions({})}>Clear Positions</button></div><div className="vg-floor-layout"><aside className="vg-floor-side"><h3>Camera Inventory</h3><p>{visible.length} cameras visible</p>{visible.slice(0,80).map(c=><button key={`${c.nvr}:${c.id}`} className={selected===`${c.nvr}:${c.id}`?"active":""} onClick={()=>setSelected(`${c.nvr}:${c.id}`)}><span className={`dot ${String(c.status).toLowerCase()==="online"?"online":"offline"}`}/><span>{c.name}<small>{c.nvr} · CH-{c.id}</small></span></button>)}</aside><main className="vg-floor-canvas"><div className="vg-map-title">{mapName}<span>{selected?"Click map to place selected camera":"Select a camera first"}</span></div><div ref={mapRef} onClick={place} className={`vg-map ${selected?"placing":""}`}>{image?<img src={image} alt="Floor plan"/>:<div className="vg-map-empty"><b>Upload a floor plan</b><span>PNG, JPG or WEBP</span></div>}{Object.entries(positions).map(([key,pos])=>{const c=cameras.find(x=>`${x.nvr}:${x.id}`===key);return c?<div className="vg-map-pin" key={key} style={{left:`${pos.x}%`,top:`${pos.y}%`}} title={`${c.name} | ${c.nvr} CH-${c.id}`}>📹<span>{c.name}</span></div>:null})}</div></main></div></div>
}
