import { useEffect, useMemo, useState } from "react";
import Loader from "../components/Loader";
import api from "../services/api";
import "./Users.css";

const roleLabel = (role) => { const v=String(role||"").toLowerCase(); if(v.includes("admin"))return "Administrator"; if(v.includes("operator"))return "Operator"; if(v.includes("viewer"))return "Viewer"; return role||"User"; };
const userKey=(n,u)=>`${n.nvr_id}:${u.id}`;

export default function Users(){
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[query,setQuery]=useState(""),[filter,setFilter]=useState("ALL"),[selected,setSelected]=useState([]),[saving,setSaving]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const load=async()=>{try{setError("");const r=await api.get("/nvr/users/summary");setData(r.data);}catch(e){setError(e.response?.data?.detail||e.message||"Unable to load NVR users");}finally{setLoading(false)}};
 useEffect(()=>{load();const t=setInterval(load,30000);return()=>clearInterval(t)},[]);
 const filtered=(data?.nvrs||[]).filter(n=>{if(filter!=="ALL"&&n.status!==filter)return false;const q=query.trim().toLowerCase();return !q||[n.nvr,n.ip,...(n.users||[]).map(u=>`${u.userName} ${u.role}`)].join(" ").toLowerCase().includes(q)});
 const allVisible=filtered.flatMap(n=>(n.users||[]).map(u=>({nvr_id:n.nvr_id,nvr:n.nvr,user_id:u.id,key:userKey(n,u)}))).filter(x=>x.user_id);
 const allSelected=allVisible.length>0&&allVisible.every(x=>selected.includes(x.key));
 const toggle=(x)=>setSelected(p=>p.includes(x.key)?p.filter(k=>k!==x.key):[...p,x.key]);
 const selectAll=()=>setSelected(allSelected?[]:allVisible.map(x=>x.key));
 const apply=async(changes)=>{if(!selected.length)return;setSaving(true);setMessage("");setError("");const items=[];for(const n of (data?.nvrs||[]))for(const u of (n.users||[])){const key=userKey(n,u);if(selected.includes(key)&&u.id)items.push({nvr_id:n.nvr_id,nvr:n.nvr,user_id:u.id,changes})}try{const r=await api.put("/nvr/users/bulk-update",{items});setMessage(`${r.data.succeeded}/${r.data.total} user changes applied.`);if(r.data.failed)setError(r.data.results.filter(x=>!x.success).map(x=>`${x.nvr}: ${x.error}`).join(" | "));setSelected([]);await load()}catch(e){setError(e.response?.data?.detail||e.message||"Bulk user update failed")}finally{setSaving(false)}};
 if(loading&&!data)return <Loader text="Loading NVR Users..."/>;
 const online=data?.online_nvrs??0, configured=data?.configured_nvrs??0,totalUsers=data?.total_users??0;
 return <div className="vg-page vg-users-page">
  <div className="vg-page-header"><div><div className="vg-eyebrow">ACCESS & SECURITY</div><h1>NVR User Management</h1><p>Centralized user inventory across all NVRs with single-user and multi-NVR bulk controls.</p></div><button className="vg-primary-btn" onClick={load}>↻ Refresh Users</button></div>
  {message&&<div className="vg-success-banner">✓ {message}</div>}{error&&<div className="vg-user-error vg-page-error">{error}</div>}
  <div className="vg-stat-grid"><div className="vg-stat-card"><span>Total Accounts</span><strong>{totalUsers}</strong><small>Across all configured NVRs</small></div><div className="vg-stat-card"><span>NVR Availability</span><strong className="success">{online}/{configured}</strong><small>NVRs currently online</small></div><div className="vg-stat-card"><span>Selected Accounts</span><strong>{selected.length}</strong><small>Ready for bulk action</small></div></div>
  <div className="vg-toolbar-card"><div className="vg-search-wrap"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search NVR, IP, username or role..."/></div><div className="vg-filter-group">{["ALL","ONLINE","ERROR"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div><button className="vg-select-btn" onClick={selectAll}>{allSelected?"Clear Visible":"Select Visible"}</button></div>
  <div className="vg-bulk-bar"><span>{selected.length} selected</span><button disabled={!selected.length||saving} onClick={()=>apply({enabled:true})}>Enable Selected</button><button disabled={!selected.length||saving} onClick={()=>apply({enabled:false})}>Disable Selected</button><select disabled={!selected.length||saving} defaultValue="" onChange={e=>{if(e.target.value)apply({role:e.target.value});e.target.value=""}}><option value="">Change Role…</option><option value="Administrator">Administrator</option><option value="Operator">Operator</option><option value="Viewer">Viewer</option></select><small>Password changes are intentionally not bulk-enabled for safety.</small></div>
  <div className="vg-user-grid">{filtered.map(nvr=><section className="vg-user-card" key={nvr.nvr}><header className="vg-user-card-head"><div><div className="vg-nvr-title"><span className={`vg-status-dot ${nvr.status==="ONLINE"?"online":"offline"}`}/>{nvr.nvr}</div><div className="vg-nvr-ip">{nvr.ip||"IP unavailable"}</div></div><span className={`vg-status-pill ${nvr.status==="ONLINE"?"online":"offline"}`}>{nvr.status||"UNKNOWN"}</span></header><div className="vg-user-summary"><div><span>Users</span><strong>{nvr.user_count??0}</strong></div><div><span>Access</span><strong>{nvr.status==="ONLINE"?"Active":"Review"}</strong></div></div>{nvr.error&&<div className="vg-user-error">{nvr.error}</div>}<div className="vg-user-table-wrap"><table className="vg-user-table"><thead><tr><th></th><th>Username</th><th>Role</th><th>Status</th></tr></thead><tbody>{(nvr.users||[]).length?nvr.users.map((u,i)=>{const enabled=String(u.enabled).toLowerCase()!=="false",key=userKey(nvr,u);return <tr key={`${nvr.nvr}-${u.id||i}`}><td><input type="checkbox" checked={selected.includes(key)} onChange={()=>toggle({nvr_id:nvr.nvr_id,nvr:nvr.nvr,user_id:u.id,key})} disabled={!u.id}/></td><td><strong>{u.userName||"—"}</strong></td><td><span className="vg-role-badge">{roleLabel(u.role)}</span></td><td><span className={`vg-enabled ${enabled?"yes":"no"}`}>{enabled?"Active":"Disabled"}</span></td></tr>}) : <tr><td colSpan="4" className="vg-empty-cell">No user accounts returned by this NVR.</td></tr>}</tbody></table></div></section>)}</div>
 </div>;
}
