# ==========================================================
# VisionGuard AI Enterprise Configuration
# Tata 1mg - NVR Security Operations Center
# ==========================================================

# ==========================================================
# Organization
# ==========================================================

ORGANIZATION_NAME = "Tata 1mg"

SYSTEM_NAME = "NVR Security Operations Center"

APPLICATION_NAME = (
    f"{ORGANIZATION_NAME} {SYSTEM_NAME}"
)

APPLICATION_VERSION = "3.4 Enterprise"


# ==========================================================
# Dashboard Configuration
# ==========================================================

AUTO_REFRESH_SECONDS = 5
POLLING_INTERVAL = 5
RECORDING_LOSS_THRESHOLD_SECONDS = 600  # 10 minutes - alert after a verified recording gap exceeds this threshold
ALERT_DELAY_SECONDS = 15
CAMERAS_PER_PAGE = 25

DEFAULT_SORT = "camera"
DEFAULT_STATUS_FILTER = "ALL"

ENABLE_DUPLICATE_PROTECTION = True


# ==========================================================
# Email Configuration
# ==========================================================

EMAIL_ALERT_ENABLED = True

EMAIL_BRAND = APPLICATION_NAME

EMAIL_FOOTER = (
    "This is an automated alert generated by "
    "VisionGuard AI Enterprise Monitoring Platform."
)

EMAIL_COOLDOWN_MINUTES = 15
ENABLE_EMAIL_LOGGING = True
MAX_EMAIL_RETRY = 3
SMTP_TIMEOUT = 15


# ==========================================================
# SMTP Configuration
# ==========================================================

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

SMTP_USERNAME = "zubair.khan@1mg.com"

# Keep the same Gmail App Password
# that is already configured in your current config.py.
SMTP_PASSWORD = "garajkqynquqccpe"

RECEIVER_EMAIL = "zubair.khan@1mg.com"


# ==========================================================
# Alert Configuration
# ==========================================================

ENABLE_CAMERA_OFFLINE_ALERT = True
ENABLE_CAMERA_RECOVERY_ALERT = True

ENABLE_IDENTITY_ALERT = True

ENABLE_IP_CONFLICT_ALERT = True
ENABLE_IP_CONFLICT_RECOVERY = True

ENABLE_VIDEO_LOSS_ALERT = True
ENABLE_STORAGE_FAILURE_ALERT = True
ENABLE_NETWORK_ALERT = True
ENABLE_POWER_FAILURE_ALERT = True
ENABLE_CAMERA_TAMPERING_ALERT = True

ENABLE_ANALYTICS_REPORT = True


# ==========================================================
# Dashboard Status
# ==========================================================

STATUS_ONLINE = "Online"
STATUS_OFFLINE = "Offline"
STATUS_WARNING = "Warning"
STATUS_UNKNOWN = "Unknown"


# ==========================================================
# UI Colors
# ==========================================================

COLOR_ONLINE = "#22C55E"
COLOR_OFFLINE = "#EF4444"
COLOR_WARNING = "#F59E0B"
COLOR_INFO = "#2563EB"
COLOR_CRITICAL = "#DC2626"


# ==========================================================
# HIKVISION NVR CONFIGURATION
# ==========================================================
#
# Total NVRs = 9
#
# Camera count is NOT hardcoded.
# Cameras will be discovered automatically
# from each NVR.
#
# NVR-1 to NVR-5 = Existing
# NVR-6 to NVR-9 = Newly added
#
# ==========================================================

NVRS = [

    # ======================================================
    # NVR-1
    # ======================================================

    {
        "id": 1,
        "name": "NVR-1",
        "ip": "192.168.1.5",
        "port": 82,
        "rtsp_port": 3011,
        "username": "admin",
        "password": "Stark@#$24",
    },


    # ======================================================
    # NVR-2
    # ======================================================

    {
        "id": 2,
        "name": "NVR-2",
        "ip": "192.168.1.6",
        "port": 85,
        "rtsp_port": 3019,
        "username": "admin",
        "password": "Stark@#$24",
    },


    # ======================================================
    # NVR-3
    # ======================================================

    {
        "id": 3,
        "name": "NVR-3",
        "ip": "192.168.1.4",
        "port": 81,
        "rtsp_port": 3012,
        "username": "admin",
        "password": "Stark@#$24",
    },


    # ======================================================
    # NVR-4
    # ======================================================

    {
        "id": 4,
        "name": "NVR-4",
        "ip": "192.168.1.3",
        "port": 83,
        "rtsp_port": 3013,
        "username": "admin",
        "password": "Stark@#$24",
    },


    # ======================================================
    # NVR-5
    # ======================================================

    {
        "id": 5,
        "name": "NVR-5",
        "ip": "192.168.1.7",
        "port": 84,
        "rtsp_port": 3014,
        "username": "admin",
        "password": "Stark@#$24",
    },


    # ======================================================
    # NVR-6
    # ======================================================

    {
        "id": 6,
        "name": "NVR-6",
        "ip": "192.168.1.8",
        "port": 86,
        "rtsp_port": 3015,
        "username": "admin",
        "password": "Stark@#$24",
    },


    # ======================================================
    # NVR-7
    # ======================================================

    {
        "id": 7,
        "name": "NVR-7",
        "ip": "192.168.1.9",
        "port": 88,
        "rtsp_port": 3016,
        "username": "admin",
        "password": "Stark@#$24",
    },


    # ======================================================
    # NVR-8
    # ======================================================

    {
        "id": 8,
        "name": "NVR-8",
        "ip": "192.168.1.10",
        "port": 89,
        "rtsp_port": 3017,
        "username": "admin",
        "password": "Stark@#$24",
    },


    # ======================================================
    # NVR-9
    # ======================================================

    {
        "id": 9,
        "name": "NVR-9",
        "ip": "192.168.1.11",
        "port": 90,
        "rtsp_port": 3018,
        "username": "admin",
        "password": "Stark@#$24",
    },

]


# ==========================================================
# Supported Alerts
# ==========================================================

SUPPORTED_ALERTS = [

    "Camera Offline",
    "Camera Recovery",

    "Identity Changed",

    "IP Conflict",
    "IP Conflict Resolved",

    "Video Loss",

    "Storage Failure",
    "Network Issue",
    "Power Failure",
    "Camera Tampering",

    "Analytics Report",

    "PTZ Position Changed",
    "PTZ Position Restored",

    "Camera Angle Changed",
    "Camera Angle Restored",
]


# ==========================================================
# PTZ POSITION MONITORING
# ==========================================================

PTZ_MONITOR_INTERVAL_SECONDS = 15

PTZ_CONFIRM_READINGS = 2

PTZ_POSITION_TOLERANCE = 0.5

ENABLE_PTZ_POSITION_ALERT = True


# ==========================================================
# CAMERA VIEWPOINT / ANGLE MONITORING
# ==========================================================

ANGLE_MONITOR_ENABLED = True

# Scan every 30 seconds
ANGLE_MONITOR_INTERVAL_SECONDS = 30

# Camera angle detection confirmation
ANGLE_CONFIRM_READINGS = 2


# ==========================================================
# GLOBAL CHANGE THRESHOLD
# ==========================================================

ANGLE_CHANGE_THRESHOLD = 0.030


# ==========================================================
# ORB FEATURES
# ==========================================================

ANGLE_ORB_FEATURES = 1200

ANGLE_MIN_GOOD_MATCHES = 15


# ==========================================================
# RTSP FRAME TIMEOUT
# ==========================================================

ANGLE_STREAM_READ_TIMEOUT_SECONDS = 10


# ==========================================================
# EVIDENCE
# ==========================================================

ANGLE_EVIDENCE_ENABLED = True


# ==========================================================
# GLOBAL GRID COVERAGE
# ==========================================================

ANGLE_MIN_GRID_COVERAGE = 0.33


# ==========================================================
# GLOBAL CONSISTENCY
# ==========================================================

ANGLE_MIN_GLOBAL_CONSISTENCY = 0.55


# ==========================================================
# RESTORE / LATCH
# ==========================================================

# Camera Angle Changed state remains latched.
#
# 6 consecutive successful baseline recovery
# confirmations are required.
#
# 6 x 30 seconds = approximately 3 minutes.

ANGLE_RESTORE_CONFIRM_READINGS = 6


# ==========================================================
# RESTORE SCORE
# ==========================================================

ANGLE_RESTORE_MAX_SCORE = 0.018


# ==========================================================
# PHYSICAL MOVEMENT REQUIREMENTS
# ==========================================================

ANGLE_MIN_PHYSICAL_MATCHES = 15

ANGLE_MIN_PHYSICAL_INLIERS = 10

ANGLE_MIN_PHYSICAL_INLIER_RATIO = 0.55

ANGLE_MIN_PHYSICAL_ANGLE_DEG = 1.5

ANGLE_MAX_REPROJECTION_ERROR = 6.0

ANGLE_MAX_PROJECTIVE_TERM = 0.008


# ==========================================================
# BASELINE RECOVERY REQUIREMENTS
# ==========================================================

ANGLE_RECOVERY_MIN_MATCHES = 30

ANGLE_RECOVERY_MIN_INLIERS = 20

ANGLE_RECOVERY_MIN_INLIER_RATIO = 0.65

ANGLE_RECOVERY_MIN_GRID_COVERAGE = 0.33

ANGLE_RECOVERY_MAX_REPROJECTION_ERROR = 5.0

ANGLE_RECOVERY_MAX_PROJECTIVE_TERM = 0.006


# ==========================================================
# CAMERA FOV
# ==========================================================

ANGLE_HORIZONTAL_FOV_DEG = 75.0

ANGLE_VERTICAL_FOV_DEG = 45.0


# ==========================================================
# End of Configuration
# ==========================================================